// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: wallet_gateway.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletGateway_GetWallet_FullMethodName         = "/machina.wallet.gateway.v1.WalletGateway/GetWallet"
	WalletGateway_ListWallets_FullMethodName       = "/machina.wallet.gateway.v1.WalletGateway/ListWallets"
	WalletGateway_SubmitTransaction_FullMethodName = "/machina.wallet.gateway.v1.WalletGateway/SubmitTransaction"
)

// WalletGatewayClient is the client API for WalletGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletGateway is a thin gRPC facade over the MACHINA wallet management
// service. It is intended to be deployed as a Kubernetes sidecar that other
// microservices in the same Pod can call over loopback gRPC, avoiding HTTP
// sign-on-every-request overhead in chatty workloads.
type WalletGatewayClient interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*Wallet, error)
	ListWallets(ctx context.Context, in *ListWalletsRequest, opts ...grpc.CallOption) (*WalletPage, error)
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmittedTransaction, error)
}

type walletGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletGatewayClient(cc grpc.ClientConnInterface) WalletGatewayClient {
	return &walletGatewayClient{cc}
}

func (c *walletGatewayClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, WalletGateway_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletGatewayClient) ListWallets(ctx context.Context, in *ListWalletsRequest, opts ...grpc.CallOption) (*WalletPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletPage)
	err := c.cc.Invoke(ctx, WalletGateway_ListWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletGatewayClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmittedTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmittedTransaction)
	err := c.cc.Invoke(ctx, WalletGateway_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletGatewayServer is the server API for WalletGateway service.
// All implementations must embed UnimplementedWalletGatewayServer
// for forward compatibility.
//
// WalletGateway is a thin gRPC facade over the MACHINA wallet management
// service. It is intended to be deployed as a Kubernetes sidecar that other
// microservices in the same Pod can call over loopback gRPC, avoiding HTTP
// sign-on-every-request overhead in chatty workloads.
type WalletGatewayServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*Wallet, error)
	ListWallets(context.Context, *ListWalletsRequest) (*WalletPage, error)
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmittedTransaction, error)
	mustEmbedUnimplementedWalletGatewayServer()
}

// UnimplementedWalletGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletGatewayServer struct{}

func (UnimplementedWalletGatewayServer) GetWallet(context.Context, *GetWalletRequest) (*Wallet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedWalletGatewayServer) ListWallets(context.Context, *ListWalletsRequest) (*WalletPage, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWallets not implemented")
}
func (UnimplementedWalletGatewayServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmittedTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedWalletGatewayServer) mustEmbedUnimplementedWalletGatewayServer() {}
func (UnimplementedWalletGatewayServer) testEmbeddedByValue()                       {}

// UnsafeWalletGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletGatewayServer will
// result in compilation errors.
type UnsafeWalletGatewayServer interface {
	mustEmbedUnimplementedWalletGatewayServer()
}

func RegisterWalletGatewayServer(s grpc.ServiceRegistrar, srv WalletGatewayServer) {
	// If the following call panics, it indicates UnimplementedWalletGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletGateway_ServiceDesc, srv)
}

func _WalletGateway_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletGatewayServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletGateway_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletGatewayServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletGateway_ListWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletGatewayServer).ListWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletGateway_ListWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletGatewayServer).ListWallets(ctx, req.(*ListWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletGateway_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletGatewayServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletGateway_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletGatewayServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletGateway_ServiceDesc is the grpc.ServiceDesc for WalletGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "machina.wallet.gateway.v1.WalletGateway",
	HandlerType: (*WalletGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _WalletGateway_GetWallet_Handler,
		},
		{
			MethodName: "ListWallets",
			Handler:    _WalletGateway_ListWallets_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _WalletGateway_SubmitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_gateway.proto",
}
