// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: wallet_gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Chain         string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CustodyKind   string                 `protobuf:"bytes,6,opt,name=custody_kind,json=custodyKind,proto3" json:"custody_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_wallet_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_wallet_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Wallet) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Wallet) GetCustodyKind() string {
	if x != nil {
		return x.CustodyKind
	}
	return ""
}

type WalletPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Wallet              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletPage) Reset() {
	*x = WalletPage{}
	mi := &file_wallet_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletPage) ProtoMessage() {}

func (x *WalletPage) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletPage.ProtoReflect.Descriptor instead.
func (*WalletPage) Descriptor() ([]byte, []int) {
	return file_wallet_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *WalletPage) GetItems() []*Wallet {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *WalletPage) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type ListWalletsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId   string                 `protobuf:"bytes,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsRequest) Reset() {
	*x = ListWalletsRequest{}
	mi := &file_wallet_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsRequest) ProtoMessage() {}

func (x *ListWalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsRequest.ProtoReflect.Descriptor instead.
func (*ListWalletsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListWalletsRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *ListWalletsRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListWalletsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWalletsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWalletsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	AmountAtoms   string                 `protobuf:"bytes,3,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	Chain         string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	IntentKind    string                 `protobuf:"bytes,5,opt,name=intent_kind,json=intentKind,proto3" json:"intent_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_wallet_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_wallet_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitTransactionRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SubmitTransactionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SubmitTransactionRequest) GetAmountAtoms() string {
	if x != nil {
		return x.AmountAtoms
	}
	return ""
}

func (x *SubmitTransactionRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SubmitTransactionRequest) GetIntentKind() string {
	if x != nil {
		return x.IntentKind
	}
	return ""
}

type SubmittedTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ChainTxHash   string                 `protobuf:"bytes,2,opt,name=chain_tx_hash,json=chainTxHash,proto3" json:"chain_tx_hash,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmittedTransaction) Reset() {
	*x = SubmittedTransaction{}
	mi := &file_wallet_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmittedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmittedTransaction) ProtoMessage() {}

func (x *SubmittedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmittedTransaction.ProtoReflect.Descriptor instead.
func (*SubmittedTransaction) Descriptor() ([]byte, []int) {
	return file_wallet_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SubmittedTransaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SubmittedTransaction) GetChainTxHash() string {
	if x != nil {
		return x.ChainTxHash
	}
	return ""
}

func (x *SubmittedTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_wallet_gateway_proto protoreflect.FileDescriptor

const file_wallet_gateway_proto_rawDesc = "" +
	"\n" +
	"\x14wallet_gateway.proto\x12\x19machina.wallet.gateway.v1\"\xa7\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fcustody_kind\x18\x06 \x01(\tR\vcustodyKind\"f\n" +
	"\n" +
	"WalletPage\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.machina.wallet.gateway.v1.WalletR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\x94\x01\n" +
	"\x12ListWalletsRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\tR\vownerUserId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\xa1\x01\n" +
	"\x18SubmitTransactionRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12!\n" +
	"\famount_atoms\x18\x03 \x01(\tR\vamountAtoms\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12\x1f\n" +
	"\vintent_kind\x18\x05 \x01(\tR\n" +
	"intentKind\"g\n" +
	"\x14SubmittedTransaction\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\"\n" +
	"\rchain_tx_hash\x18\x02 \x01(\tR\vchainTxHash\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xcc\x02\n" +
	"\rWalletGateway\x12[\n" +
	"\tGetWallet\x12+.machina.wallet.gateway.v1.GetWalletRequest\x1a!.machina.wallet.gateway.v1.Wallet\x12c\n" +
	"\vListWallets\x12-.machina.wallet.gateway.v1.ListWalletsRequest\x1a%.machina.wallet.gateway.v1.WalletPage\x12y\n" +
	"\x11SubmitTransaction\x123.machina.wallet.gateway.v1.SubmitTransactionRequest\x1a/.machina.wallet.gateway.v1.SubmittedTransactionBOZMgithub.com/machina-xyz/machina-wallet-sdk-go/examples/grpc-microservice/pb;pbb\x06proto3"

var (
	file_wallet_gateway_proto_rawDescOnce sync.Once
	file_wallet_gateway_proto_rawDescData []byte
)

func file_wallet_gateway_proto_rawDescGZIP() []byte {
	file_wallet_gateway_proto_rawDescOnce.Do(func() {
		file_wallet_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_gateway_proto_rawDesc), len(file_wallet_gateway_proto_rawDesc)))
	})
	return file_wallet_gateway_proto_rawDescData
}

var file_wallet_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wallet_gateway_proto_goTypes = []any{
	(*Wallet)(nil),                   // 0: machina.wallet.gateway.v1.Wallet
	(*WalletPage)(nil),               // 1: machina.wallet.gateway.v1.WalletPage
	(*GetWalletRequest)(nil),         // 2: machina.wallet.gateway.v1.GetWalletRequest
	(*ListWalletsRequest)(nil),       // 3: machina.wallet.gateway.v1.ListWalletsRequest
	(*SubmitTransactionRequest)(nil), // 4: machina.wallet.gateway.v1.SubmitTransactionRequest
	(*SubmittedTransaction)(nil),     // 5: machina.wallet.gateway.v1.SubmittedTransaction
}
var file_wallet_gateway_proto_depIdxs = []int32{
	0, // 0: machina.wallet.gateway.v1.WalletPage.items:type_name -> machina.wallet.gateway.v1.Wallet
	2, // 1: machina.wallet.gateway.v1.WalletGateway.GetWallet:input_type -> machina.wallet.gateway.v1.GetWalletRequest
	3, // 2: machina.wallet.gateway.v1.WalletGateway.ListWallets:input_type -> machina.wallet.gateway.v1.ListWalletsRequest
	4, // 3: machina.wallet.gateway.v1.WalletGateway.SubmitTransaction:input_type -> machina.wallet.gateway.v1.SubmitTransactionRequest
	0, // 4: machina.wallet.gateway.v1.WalletGateway.GetWallet:output_type -> machina.wallet.gateway.v1.Wallet
	1, // 5: machina.wallet.gateway.v1.WalletGateway.ListWallets:output_type -> machina.wallet.gateway.v1.WalletPage
	5, // 6: machina.wallet.gateway.v1.WalletGateway.SubmitTransaction:output_type -> machina.wallet.gateway.v1.SubmittedTransaction
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wallet_gateway_proto_init() }
func file_wallet_gateway_proto_init() {
	if File_wallet_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_gateway_proto_rawDesc), len(file_wallet_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_gateway_proto_goTypes,
		DependencyIndexes: file_wallet_gateway_proto_depIdxs,
		MessageInfos:      file_wallet_gateway_proto_msgTypes,
	}.Build()
	File_wallet_gateway_proto = out.File
	file_wallet_gateway_proto_goTypes = nil
	file_wallet_gateway_proto_depIdxs = nil
}
